alias s='sudo'
alias ll='ls -lah'
alias c='bundle exec cucumber'
alias b='bundle'
alias be='bundle exec'
alias bl='bundle list'
alias bo='bundle open'
alias bu='bundle update'
alias m='bundle exec rake db:migrate && bundle exec rake db:migrate RAILS_ENV=test'
alias i='bundle exec rake i18n:js:export'
alias gam='git commit --amend -C head -a'
alias t='bin/teaspoon'
alias ti='bin/teaspoon -s integration'
alias pse='ps -e | grep'
