alias s='sudo'
alias ll='ls -lah'
alias b='bundle'
alias be='bundle exec'
alias bo='bundle open'
alias bu='bundle update'
alias m='bundle exec rake db:migrate && bundle exec rake db:migrate RAILS_ENV=test'
alias i='bundle exec rake i18n:js:export'
alias gam='git commit --amend -C HEAD -a'
alias pse='ps -e | grep'
alias d=docker
alias dc=docker-compose
alias rm='rm -fr'
alias p='ping db.de'
alias gg='git log --graph --format="%C(white)%h:%Creset %s (%C(cyan)%an, %ar%Creset)%d"'
